services:
  # ======================================
  # Conductor
  # ======================================
  # Conductor is a lightweight Alpine-based container that automates configuration tasks and initialization events
  # All scripts can be view from the repos conductorScripts folder
  #
  # .
  # └── conductorScripts/
  #   ├── /deployment
  #   └── /services
  #
  # - Services contains modular scripts for individual service setup tasks. Each file is named according to its purpose, with inline comments documenting the code.
  # - Deployments contains scripts that execute service scripts sequentially based on the deployment configuration. These also include custom post-deployment logs with essential next steps for the deployment scenario.
  #
  # For more info see the follow documentation: https://main--overturedev.netlify.app/docs/other-software/conductor/
  # --------------------------------------
  conductor:
    profiles: ["platform"]
    image: alpine/curl:8.8.0
    container_name: conductor
    ports:
      - "9204:9204"
    volumes:
      - ./configurationFiles/elasticsearchConfigs/correlation_index_template.json:/usr/share/elasticsearch/config/correlation_index_template.json
      - ./configurationFiles/elasticsearchConfigs/mutation_index_template.json:/usr/share/elasticsearch/config/mutation_index_template.json
      - ./configurationFiles/elasticsearchConfigs/mrna_index_template.json:/usr/share/elasticsearch/config/mrna_index_template.json
      - ./configurationFiles/elasticsearchConfigs/protein_index_template.json:/usr/share/elasticsearch/config/protein_index_template.json
      - ./conductorScripts:/scripts
      - ./health:/health
    environment:
      - PROFILE=${PROFILE:-platform}
    command: >
      sh -c '
        set -e
          echo "Profile is set to: $PROFILE"
          case "$PROFILE" in
            platform)
              echo "Running platform deployment..."
              chmod +x scripts/deployments/platform.sh
              scripts/deployments/platform.sh
              ;;
            *)
              echo "Invalid profile: $PROFILE. Available options are [platform, correlation, mutation]."
              exit 1
              ;;
          esac
        exit 0
      '
    healthcheck:
      test: ["CMD", "test", "-f", "/health/conductor_health"]
      interval: 5s
      timeout: 40s
      retries: 100
      start_period: 30s
    networks:
      - conductor-network

  # ======================================
  # Elasticsearch
  # ======================================
  # Search and analytics engine used to help query massive datasets flexibly and efficiently.
  # Documentation Link: https://www.overture.bio/documentation/guides/deployment/dataportal/#setting-up-elasticsearch
  # --------------------------------------
  elasticsearch:
    profiles: ["platform"]
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
    container_name: elasticsearch
    platform: linux/amd64
    ports:
      - "9200:9200"
    environment:
      PUID: 3381
      PGID: 100
      discovery.type: single-node
      cluster.name: workflow.elasticsearch
      ES_JAVA_OPTS: -Xms8g -Xmx8g
      ELASTIC_PASSWORD: myelasticpassword
      xpack.security.enabled: "true"
      MANAGE_INDEX_TEMPLATES: "true"
      NETWORK_HOST: http://localhost:9200
      bootstrap.memory_lock: "true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          cpus: '6'
          memory: 16G
        reservations:
          cpus: '2'
          memory: 8G
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      - elasticsearch-logs:/usr/share/elasticsearch/logs
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    healthcheck:
      test: "curl --silent --fail localhost:9200/_cluster/health?wait_for_status=yellow&timeout=50s || exit 1"
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 25s
    networks:
      - conductor-network

  # ======================================
  # Arranger-Server Correlations
  # ======================================
  # Search API generation with compatible search UI components
  # Documentation Link: https://www.overture.bio/documentation/guides/deployment/dataportal/#running-arranger
  # --------------------------------------
  arranger-correlation:
    profiles: ["platform"]
    image: ghcr.io/overture-stack/arranger-server:3.0.0-beta.35
    container_name: arranger-correlation
    platform: linux/amd64
    depends_on:
      conductor:
        condition: service_healthy
    ports:
      - "5050:5050"
    volumes:
     - ./configurationFiles/arrangerConfigs/correlationConfigs/base.json:/app/modules/server/configs/base.json
     - ./configurationFiles/arrangerConfigs/correlationConfigs/extended.json:/app/modules/server/configs/extended.json
     - ./configurationFiles/arrangerConfigs/correlationConfigs/facets.json:/app/modules/server/configs/facets.json
     - ./configurationFiles/arrangerConfigs/correlationConfigs/matchbox.json:/app/modules/server/configs/matchbox.json
     - ./configurationFiles/arrangerConfigs/correlationConfigs/table.json:/app/modules/server/configs/table.json
    environment:
      # Arranger Variables
      PORT: 5050
      ENABLE_LOGS: false
      # Elasticsearch Variables
      ES_HOST: http://elasticsearch:9200
      ES_USER: elastic
      ES_PASS: myelasticpassword
      ES_ARRANGER_SET_INDEX: correlation_arranger_set
      DEBUG: true
    networks:
      - conductor-network

  # ======================================
  # Arranger-Server Mutations
  # ======================================
  # Search API generation with compatible search UI components
  # Documentation Link: https://www.overture.bio/documentation/guides/deployment/dataportal/#running-arranger
  # Check logs on arranger server for manifest columns
  # --------------------------------------
  arranger-mutation:
    profiles: ["platform"]
    image: ghcr.io/overture-stack/arranger-server:3.0.0-beta.35
    container_name: arranger-mutation
    platform: linux/amd64
    depends_on:
      conductor:
        condition: service_healthy
    ports:
      - "5051:5051"
    volumes:
     - ./configurationFiles/arrangerConfigs/mutationConfigs/base.json:/app/modules/server/configs/base.json
     - ./configurationFiles/arrangerConfigs/mutationConfigs/extended.json:/app/modules/server/configs/extended.json
     - ./configurationFiles/arrangerConfigs/mutationConfigs/facets.json:/app/modules/server/configs/facets.json
     - ./configurationFiles/arrangerConfigs/mutationConfigs/matchbox.json:/app/modules/server/configs/matchbox.json
     - ./configurationFiles/arrangerConfigs/mutationConfigs/table.json:/app/modules/server/configs/table.json
    environment:
      # Arranger Variables
      PORT: 5051
      ENABLE_LOGS: false
      # Elasticsearch Variables
      ES_HOST: http://elasticsearch:9200
      ES_USER: elastic
      ES_PASS: myelasticpassword
      ES_ARRANGER_SET_INDEX: mutation_arranger_set
      DEBUG: true
    networks:
      - conductor-network

  # ======================================
  # Arranger-Server MRNA
  # ======================================
  # Search API generation with compatible search UI components
  # Documentation Link: https://www.overture.bio/documentation/guides/deployment/dataportal/#running-arranger
  # --------------------------------------
  arranger-mrna:
    profiles: ["platform"]
    image: ghcr.io/overture-stack/arranger-server:3.0.0-beta.35
    container_name: arranger-mrna
    platform: linux/amd64
    depends_on:
      conductor:
        condition: service_healthy
    ports:
      - "5052:5052"
    volumes:
     - ./configurationFiles/arrangerConfigs/mrnaConfigs/base.json:/app/modules/server/configs/base.json
     - ./configurationFiles/arrangerConfigs/mrnaConfigs/extended.json:/app/modules/server/configs/extended.json
     - ./configurationFiles/arrangerConfigs/mrnaConfigs/facets.json:/app/modules/server/configs/facets.json
     - ./configurationFiles/arrangerConfigs/mrnaConfigs/matchbox.json:/app/modules/server/configs/matchbox.json
     - ./configurationFiles/arrangerConfigs/mrnaConfigs/table.json:/app/modules/server/configs/table.json
    environment:
      # Arranger Variables
      PORT: 5052
      ENABLE_LOGS: false
      # Elasticsearch Variables
      ES_HOST: http://elasticsearch:9200
      ES_USER: elastic
      ES_PASS: myelasticpassword
      ES_ARRANGER_SET_INDEX: mrna_arranger_set
      DEBUG: true
    networks:
      - conductor-network

  # ======================================
  # Arranger-Server protein
  # ======================================
  # Search API generation with compatible search UI components
  # Documentation Link: https://www.overture.bio/documentation/guides/deployment/dataportal/#running-arranger
  # --------------------------------------
  arranger-protein:
    profiles: ["platform"]
    image: ghcr.io/overture-stack/arranger-server:3.0.0-beta.35
    container_name: arranger-protein
    platform: linux/amd64
    depends_on:
      conductor:
        condition: service_healthy
    ports:
      - "5053:5053"
    volumes:
     - ./configurationFiles/arrangerConfigs/proteinConfigs/base.json:/app/modules/server/configs/base.json
     - ./configurationFiles/arrangerConfigs/proteinConfigs/extended.json:/app/modules/server/configs/extended.json
     - ./configurationFiles/arrangerConfigs/proteinConfigs/facets.json:/app/modules/server/configs/facets.json
     - ./configurationFiles/arrangerConfigs/proteinConfigs/matchbox.json:/app/modules/server/configs/matchbox.json
     - ./configurationFiles/arrangerConfigs/proteinConfigs/table.json:/app/modules/server/configs/table.json
    environment:
      # Arranger Variables
      PORT: 5053
      ENABLE_LOGS: false
      # Elasticsearch Variables
      ES_HOST: http://elasticsearch:9200
      ES_USER: elastic
      ES_PASS: myelasticpassword
      ES_ARRANGER_SET_INDEX: protein_arranger_set
      DEBUG: true
    networks:
      - conductor-network

  # ======================================
  # Stage run this locally
  # ======================================
  # The react-based, front end portal UI for Overture
  # Documentation Link: https://www.overture.bio/documentation/guides/deployment/dataportal/#setting-up-stage
  # --------------------------------------
  multi-stage:
    profiles: ["platform"]
    image: multi-stage:3.0
    container_name: multi-stage
    pull_policy: never
    platform: linux/arm64/v8
    depends_on:
      conductor:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      # Stage Variables
      NEXTAUTH_URL: http://localhost:3000/api/auth
      NEXT_PUBLIC_LAB_NAME: Drug Discovery POC
      NEXT_PUBLIC_ADMIN_EMAIL: example@example.com
      NEXT_PUBLIC_DEBUG: true
      NEXT_PUBLIC_SHOW_MOBILE_WARNING: true
      NEXT_PUBLIC_ENABLE_DOWNLOADS: true
      # Correlation Arranger Variables
      NEXT_PUBLIC_ARRANGER_CORRELATION_API: http://localhost:5050/graphql # Updated inline with nginx reverse proxy
      NEXT_PUBLIC_ARRANGER_CORRELATION_DOCUMENT_TYPE: file
      NEXT_PUBLIC_ARRANGER_CORRELATION_INDEX: correlation_centric
      # Mutation Arranger Variables
      NEXT_PUBLIC_ARRANGER_MUTATION_API: http://localhost:5051/graphql # Updated inline with nginx reverse proxy
      NEXT_PUBLIC_ARRANGER_MUTATION_DOCUMENT_TYPE: file
      NEXT_PUBLIC_ARRANGER_MUTATION_INDEX: mutation_centric
      # MRNA Arranger Variables
      NEXT_PUBLIC_ARRANGER_MRNA_API: http://localhost:5052/graphql # Updated inline with nginx reverse proxy
      NEXT_PUBLIC_ARRANGER_MRNA_DOCUMENT_TYPE: file
      NEXT_PUBLIC_ARRANGER_MRNA_INDEX: mrna_centric
      # protein Arranger Variables
      NEXT_PUBLIC_ARRANGER_PROTEIN_API: http://localhost:5053/graphql # Updated inline with nginx reverse proxy
      NEXT_PUBLIC_ARRANGER_PROTEIN_DOCUMENT_TYPE: file
      NEXT_PUBLIC_ARRANGER_PROTEIN_INDEX: protein_centric
    networks:
      - conductor-network

volumes:
  elasticsearch-data:
    driver: local
    driver_opts:
      device: ./volumes/es-data
      o: bind
      type: none
  elasticsearch-logs:
    driver: local
    driver_opts:
      device: ./volumes/es-logs
      o: bind
      type: none

networks:
  conductor-network:
    driver: bridge