services:
  # ================================================================================== #
  #  This docker-"composer" provides accessilbe configuration generation functionality #
  #  If you wish to run composer outside of docker:                                    #
  #      1. cd ./apps/composer                                                         #
  #      2. npm install && npm run build && npm install -g                             #
  # ================================================================================== #
  composer:
    profiles:
      [
        "generatePhaseOneConfigs",
        "generatePhaseTwoConfigs",
        "generatePhaseThreeConfigs",
      ]
    image: node:22-alpine
    container_name: composer
    ports:
      - "9205:9205"
    volumes:
      - ./apps/composer:/composer
      - ./apps/conductor:/conductor
      - ./data:/data
      - ./docker-compose.yml:/docker-compose.yml
    environment:
      PROFILE: ${PROFILE:-default}
      # User Input Path
      CSV_FILE(S):
      JSON_FILE(S):
      # Future input path
      COMPOSITION_FILE:
      # Output Directory
      CONFIG_DIR: ../conductor/configs/
    working_dir: /composer
    command: >
      sh -c '
        set -e
        echo "Profile is set to: $PROFILE"
        # Install dependencies and build
        npm install
        npm run build
        npm install -g .
        case "$PROFILE" in
          "generatePhaseOneConfigs")
            composer -p generateElasticsearchMapping -f $CSV_FILE $JSON_FILE -o $CONFIG_DIR 
            composer -p generateArrangerSchema -f CONFIG_DIR/mapping.json -o $CONFIG_DIR 
            ;;
          "generatePhaseTwoConfigs")
            composer -p generateLecternSchema -f $CSV_FILE(S) -o $CONFIG_DIR 
            ;;
          "generatePhaseThreeConfigs")
            composer -p generateSongSchema -f $JSON_METADATA -o $CONFIG_DIR 
            ;;
          *)
            echo "Invalid profile specified: $PROFILE" &&
            ;;
        esac
      '
    networks:
      - conductor-network

networks:
  conductor-network:
    name: conductor-network
