services:
  composer:
    profiles: ["generatePhaseOneConfigs", "default"]
    image: node:22-alpine
    container_name: composer
    ports:
      - "9205:9205"
    volumes:
      - ./apps/composer:/composer
      - ./apps/conductor:/conductor
      - ./data:/data
      - ./docker-compose.yml:/docker-compose.yml
    environment:
      PROFILE: ${PROFILE:-default}
      # User Input Paths
      TABULAR_INDEX_NAMES: sample, summary, id
      TABULAR_SAMPLE_DATA: /data/sampleData.csv, /data/summaryData.csv, /data/idMappingDb.csv,
      # Output Directories
      ES_CONFIG_DIR: ../conductor/configs/elasticsearchConfigs
      ARRANGER_CONFIG_DIR: ../conductor/configs/arrangerConfigs
    working_dir: /composer
    command: >
      sh -c '
        set -e
        echo "Profile is set to: $PROFILE"
        # Install dependencies and build
        npm install
        npm run build
        npm install -g .
        case "$PROFILE" in
          "generatePhaseOneConfigs")
            echo "Generating Elasticsearch Mapping..." &&
            chmod +x /composer/scripts/generateElasticSearchMapping.sh
            /composer/scripts/generateElasticSearchMapping.sh
            chmod +x /composer/scripts/generateArrangerConfigs.sh
            /composer/scripts/generateArrangerConfigs.sh
            ;;
          "default")
            echo "No specific profile selected. Exiting..." &&
            tail -f /dev/null 
            ;;
          *)
            echo "Invalid profile specified: $PROFILE" &&
            tail -f /dev/null 
            ;;
        esac
      '
    networks:
      - conductor-network

networks:
  conductor-network:
    name: conductor-network
